language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
env:
  - DB=mysql
  - DB=postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install ncbi-blast+ emboss gmap
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle install
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database quorum_test;'; fi"
  - sh -c "if [ '$DB' = 'postgresql' ]; then psql -c 'create database quorum_test;' -U postgres; fi"
script: "rake travis:spec"
notifications:
  email:
    - "kas@ncgr.org"
