language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
before_install:
  - sudo apt-get update
  - sudo apt-get install ncbi-blast+ emboss
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bundle install
  - mysqladmin -u root -pNULL password root
  - echo "create database quorum_test;" | mysql -u root -proot -h localhost
  - "rake travis:create_db_config"
  - "rake app:db:schema:load"
script: "rake travis:spec"
notifications:
  email:
    - "kas@ncgr.org"
