language: ruby
rvm:
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - gemfiles/Gemfile.rails-3.2.x
before_install:
  - sudo apt-get update
  - sudo apt-get install ncbi-blast+ emboss

# Create MySQL database and spec/dummy/config/database.yml
before_script:
  - "export DISPLAY=:53331.0"
  - "sh -e /etc/init.d/xvfb start"
  - mysql -e 'create database quorum_test;'
  - bundle install
  - "rake app:db:schema:load"

script: "rake travis:spec"

notifications:
  email:
    - "kas@ncgr.org"
