development:
  max_sequence_size:
  gmap:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
    bin: "%{RAILS_ROOT}/quorum/bin"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    gmap_db_dir: "%{RAILS_ROOT}/quorum/gmapdb"
    gmap_db:
      "tmp": test
    gmap_max_internal_intron_len:
    gmap_max_total_intron_len:
    gmap_threads:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
    bin: "%{RAILS_ROOT}/quorum/bin"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    blastn:
      "tmp": test
    blastx:
      "tmp": test
    tblastn:
      "tmp": test
    blastp:
      "tmp": test
    blast_threads: 4

test:
  max_sequence_size:
  gmap:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
    bin: "%{RAILS_ROOT}/quorum/bin"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    gmap_db_dir: "%{RAILS_ROOT}/quorum/gmapdb"
    gmap_db:
      "tmp": test
    gmap_max_internal_intron_len:
    gmap_max_total_intron_len:
    gmap_threads:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
    bin: "%{RAILS_ROOT}/quorum/bin"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    blastn:
      "tmp": test
    blastx:
      "tmp": test
    tblastn:
      "tmp": test
    blastp:
      "tmp": test
    blast_threads:

production:
  max_sequence_size:
  gmap:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
    bin:
    log_dir:
    tmp_dir:
    gmap_db_dir:
    gmap_db:
    gmap_max_internal_intron_len:
    gmap_max_total_intron_len:
    gmap_threads:
  blast:
    remote: true
    ssh_host:
    ssh_user:
    ssh_options:
    bin:
    log_dir:
    tmp_dir:
    blast_db:
    blastn:
    blastx:
    tblastn:
    blastp:
    blast_threads:
