# Quorum Settings
#
# ==> General
# Quorum initializer safely substitutes %{RAILS_ROOT} with ::Rails.root.to_s.
# 
# ==> NCBI BLAST+ Settings
# blast:
#   remote: true to execute script on remote machine via
#     Net::SSH. false to execute locally via Kernel#system.
#     See Net::SSH for more information.
#     http://net-ssh.github.com/ssh/v2/api/index.html
#
#   ssh_host: Net::SSH.start() host.
#
#   ssh_user: Net::SSH.start() user.
#
#   ssh_options: Net::SSH.start() optional params.
#     See http://net-ssh.github.com/ssh/v2/api/classes/Net/SSH.html#M000002
#     for a complete list of options.
#     Example Usage:
#     ssh_options:
#       password: "secret password"
#       port: 8888
#
#   script: Absolute path to search script.
#
#   log_dir: Absolute path to log file directory.
#
#   tmp_dir: Absolute path to tmp file directory.
#
#   blast_db: Absolute path to NCBI Blast database directory.
#     Execute the rake task below to build your Blast DB.
#     rake quorum:blastdb:build
#
#   blastn: Collection of Blast DBs under the parent blast_db
#     to use with blastn.
#     Example Usage:
#     blastn:
#       "Display name": blastn_database_name
#       "A really cool genome": really_cool_genome
#
#   blastx: Collection of Blast DBs under the parent blast_db
#     to use with blastx.
#     Example Usage:
#     blastx:
#       "Display name": blastx_database_name
#       "A really cool genome": really_cool_genome
#
#   tblastn: Collection of Blast DBs under the parent blast_db
#     to use with tblastn.
#     Example Usage:
#     tblastn:
#       "Display name": tblastn_database_name
#       "A really cool genome": really_cool_genome
#
#   blastp: Collection of Blast DBs under the parent blast_db
#     to use with blastp.
#     Example Usage:
#     blastp:
#       "Display name": blastp_database_name
#       "A really cool genome": really_cool_genome
#
#   blast_threads: Number of Blast threads. >= 1
#     Defaults to 1.

development:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script: "%{RAILS_ROOT}/quorum/bin/search"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    blastn:
      "camptotheca_acuminata-20101112": camptotheca_acuminata-20101112
      "colchicum_autumnale-20101112": colchicum_autumnale-20101112
    blastx:
      "camptotheca_acuminata-20101112": camptotheca_acuminata-20101112
      "colchicum_autumnale-20101112": colchicum_autumnale-20101112
    tblastn:
      "camptotheca_acuminata-20101112": camptotheca_acuminata-20101112
      "colchicum_autumnale-20101112": colchicum_autumnale-20101112
    blastp:
      "camptotheca_acuminata-20101112": camptotheca_acuminata-20101112
      "colchicum_autumnale-20101112": colchicum_autumnale-20101112
    blast_threads: 4

test:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script: "%{RAILS_ROOT}/quorum/bin/search"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    blastn:
      "tmp": test
    blastx:
      "tmp": test
    tblastn:
      "tmp": test
    blastp:
      "tmp": test
    blast_threads:

production:
  blast:
    remote: true
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script:
    log_dir:
    tmp_dir:
    blast_db:
    blastn:
      # Example:
      # "Display name": blastn_database_name
      # "A really cool genome": really_cool_genome
    blastx:
      # Example:
      # "Display name": blastx_database_name
      # "A really cool genome": really_cool_genome
    tblastn:
      # Example:
      # "Display name": tblastn_database_name
      # "A really cool genome": really_cool_genome
    blastp:
      # Example:
      # "Display name": blastp_database_name
      # "A really cool genome": really_cool_genome
    blast_threads:
