# Quorum Settings
#
# ==> General
# Quorum initializer safely substitutes %{RAILS_ROOT} with
# ::Rails.root.to_s.
# 
# ==> NCBI BLAST Plus Settings
# blast:
#   remote: true to execute script on remote machine via
#     Net::SSH. false to execute locally via Kernel#system.
#     See Net::SSH for more information.
#     http://net-ssh.github.com/ssh/v2/api/index.html
#
#   ssh_host: Net::SSH.start() host.
#
#   ssh_user: Net::SSH.start() user.
#
#   ssh_options: Net::SSH.start() optional params.
#     See http://net-ssh.github.com/ssh/v2/api/classes/Net/SSH.html#M000002
#     for a complete list of options.
#     Example Usage:
#     ssh_options:
#       password: "secret password"
#       port: 8888
#
#   script: Absolute path to option_parser script.
#
#   log_dir: Absolute path to log file directory.
#
#   tmp_dir: Absolute path to tmp file directory.
#
#   blast_db: Absolute path to NCBI Blast database directory.
#     Execute the rake task below to build your Blast DB.
#     rake quorum:blastdb:build
#
#   tblastn: Collection of Blast DBs under the parent blast_db
#     to use with tblastn.
#     Example Usage:
#     tblastn:
#       - genome_1 
#       - genome_2 
#
#   blastp: Collection of Blast DBs under the parent blast_db
#     to use with blastp.
#     Example Usage:
#     blastp:
#       - prot_1 
#       - prot_2 
#
#   blastn: Collection of Blast DBs under the parent blast_db
#     to use with blastn.
#     Example Usage:
#     blastn:
#       - genome_1 
#       - genome_2 
#
#   blastx: Collection of Blast DBs under the parent blast_db
#     to use with blastx.
#     Example Usage:
#     blastx:
#       - prot_1 
#       - prot_2 
#
#   blast_threads: Number of Blast threads. >= 1
#     Defaults to 1.
#

development:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script: "%{RAILS_ROOT}/quorum/bin/option_parser"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    tblastn:
      # Example:
      # - genome_1
      # - genome_2 
      - tmp
    blastp:
      # Example:
      # - prot_1
      # - prot_2 
      - tmp
    blastn:
      # Example:
      # - genome_1
      # - genome_2 
      - tmp
    blastx:
      # Example:
      # - prot_1
      # - prot_2 
      - tmp
    blast_threads: 4

test:
  blast:
    remote: false
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script: "%{RAILS_ROOT}/quorum/bin/option_parser"
    log_dir: "%{RAILS_ROOT}/quorum/log"
    tmp_dir: "%{RAILS_ROOT}/quorum/tmp"
    blast_db: "%{RAILS_ROOT}/quorum/blastdb"
    tblastn:
      # Example:
      # - genome_1
      # - genome_2 
      - tmp
    blastp:
      # Example:
      # - prot_1
      # - prot_2 
      - tmp
    blastn:
      # Example:
      # - genome_1
      # - genome_2 
      - tmp
    blastx:
      # Example:
      # - prot_1
      # - prot_2 
      - tmp
    blast_threads: 4

production:
  blast:
    remote: true
    ssh_host:
    ssh_user:
    ssh_options:
      # Example:
      # password: "secret password"
      # port: 8888
    script:
    log_dir:
    tmp_dir:
    blast_db:
    tblastn:
      # Example:
      # - genome_1
      # - genome_2 
    blastp:
      # Example:
      # - prot_1
      # - prot_2 
    blastn:
      # Example:
      # - genome_1
      # - genome_2 
    blastx:
      # Example:
      # - prot_1
      # - prot_2 
    blast_threads:

